# Starter pipeline azure
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:

trigger:
- main

pool: 
  vmImage: windows-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $date=$(Get-Date -Format hmmss);
      Write-Host "##vso[task.setvariable variable=version]$date"
      Write-Host "$date"
- task: UiPathPack@2
  inputs:
    versionType: 'ManualVersion'
    version: '$(version)'
    projectJsonPath: '$(Build.SourcesDirectory)'
    outputType: 'Process'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'POCProcess'
    publishLocation: 'Container'