# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:
- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(System.DefaultWorkingDirectory)/_SebastianBalan_POCProcess'
    outputType: 'Process'
    outputPath: '$(System.DefaultWorkingDirectory)/_SebastianBalan_POCProcess'
    