# Starter pipeline azure
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:

trigger:
- main

pool: 
  vmImage: windows-latest

steps:
- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    outputType: 'Process'
    orchestratorConnection: 'cloudOrch'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output'
- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'cloudOrch'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output'
    folderName: 'Seba''s folder'
    entryPoints: 'Main.xaml'