# Starter pipeline azure
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:

trigger:
- main

pool: 
  vmImage: windows-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      export date="$(date '+%H%M%S')"
      echo "##vso[task.setvariable variable=version;isOutput=true]$date"
      echo "$date"
  name: "GetVersion"
- task: UiPathPack@2
  inputs:
    versionType: 'ManualVersion'
    version: 'GetVersion.version'
    projectJsonPath: '$(Build.SourcesDirectory)'
    outputType: 'Process'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'POCProcess'
    publishLocation: 'Container'
